version: '3.9'

services:
  dauth_v2_server:
    container_name: dauth_v2_server
    image: dauth_v2_server
    build:
      context: .
      target: ${APP_ENV}
    restart: always
    ports:
      - ${SERVER_EXTERNAL_PORT}:3000
    depends_on:
      - dauth_v2_db
    volumes:
      - ./:/app
      - ./docker_volumes/logs:/app/logs
  dauth_v2_db:
    container_name: dauth_v2_db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
  phpmyadmin:
    container_name: dauth_v2_pma
    image: phpmyadmin:5.2.0
    restart: always
    depends_on:
      - dauth_v2_db
    ports:
      - ${PMA_EXTERNAL_PORT}:80
    environment:
      - PMA_HOST=dauth_v2_db
